/* Generated by tools/build/gen_man_pages.sh — DO NOT EDIT */
#ifndef _M4KK1_MAN_PAGES_H_
#define _M4KK1_MAN_PAGES_H_

struct mkrn_man_page {
    const char *name;
    int section;
    const unsigned char *data;
    unsigned int len;
};

extern const struct mkrn_man_page mkrn_man_pages[];

#endif
