.\" M4KK1 4P1 - who.1
.TH WHO 1 "2026-07-22" "M4KK1 1.0" "M4KK1 User Commands"
.SH NAME
who \- show who is logged on
.SH SYNOPSIS
.B who
.SH DESCRIPTION
Display all active login sessions. Data source: /sys/sessions/.
.SH OUTPUT FORMAT
USER     TTY     LOGIN_TIME          FROM
.SH SEE ALSO
.BR id (1),
.BR ps (1),
.BR cu (8)
