.\" M4KK1 4P1 - m4k_setuid.2
.TH M4K_SETUID 2 "2026-07-22" "M4KK1 1.0" "M4KK1 System Calls"
.SH NAME
m4k_setuid \- set user ID
.SH SYNOPSIS
.nf
#include <m4k/syscall.h>
int m4k_setuid(uid_t uid);
.fi
.SH DESCRIPTION
Set the real UID and effective UID of the calling process.
.SH RETURN VALUE
Returns 0 on success, or a negative M4K_E* error code on failure.
.SH ERRORS
.TP
.B M4K_EPERM
Caller lacks privilege
.SH SEE ALSO
.BR m4k_getuid (2),
.BR m4k_setgid (2)
