/*
 * M4KK1 4P1 - mkversion.c
 * Description: Kernel version header generator.
 *
 * Copyright (c) 2026 Yaku Makki
 * SPDX-License-Identifier: 4P1-Custom
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define VERSION_MAJOR 0
#define VERSION_MINOR 1
#define VERSION_PATCH 0

int main(int argc, char *argv[])
{
    FILE *fp;
    time_t now;
    struct tm *tm_info;
    char timestamp[64];

    /* Get current timestamp */
    time(&now);
    tm_info = localtime(&now);
    strftime(timestamp, sizeof(timestamp),
             "%Y-%m-%d %H:%M:%S", tm_info);

    /* Generate version header file */
    fp = fopen("include/version.h", "w");
    if (!fp) {
        perror("Could not create version header");
        return 1;
    }

    fprintf(fp, "/*\n");
    fprintf(fp, " * M4KK1 kernel version info\n");
    fprintf(fp, " * Auto-generated by mkversion\n");
    fprintf(fp, " */\n\n");

    fprintf(fp, "#ifndef __KERNEL_VERSION_H__\n");
    fprintf(fp, "#define __KERNEL_VERSION_H__\n\n");

    fprintf(fp, "/* Version numbers */\n");
    fprintf(fp, "#define KERNEL_VERSION_MAJOR %d\n",
            VERSION_MAJOR);
    fprintf(fp, "#define KERNEL_VERSION_MINOR %d\n",
            VERSION_MINOR);
    fprintf(fp, "#define KERNEL_VERSION_PATCH %d\n",
            VERSION_PATCH);
    fprintf(fp, "#define KERNEL_VERSION_STRING \"%d.%d.%d\"\n",
            VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH);

    fprintf(fp, "\n/* Kernel info */\n");
    fprintf(fp, "#define KERNEL_NAME \"M4KK1\"\n");
    fprintf(fp, "#define KERNEL_CODENAME \"M4KK1\"\n");
    fprintf(fp, "#define KERNEL_AUTHOR \"makkichan947\"\n");

    fprintf(fp, "\n/* Build info */\n");
    fprintf(fp, "#define KERNEL_BUILD_DATE \"%s\"\n",
            timestamp);
    fprintf(fp, "#define KERNEL_BUILD_MACHINE \"%s\"\n",
            getenv("USER") ?: "unknown");

    fprintf(fp, "\n/* Version string */\n");
    fprintf(fp,
        "#define KERNEL_FULL_VERSION "
        "KERNEL_NAME \" \" KERNEL_VERSION_STRING\n");

    fprintf(fp,
        "\n#endif /* __KERNEL_VERSION_H__ */\n");

    fclose(fp);

    printf("Version info generated to include/version.h\n");
    return 0;
}
