.\" M4KK1 4P1 - m4k_register_session.2
.TH M4K_REGISTER_SESSION 2 "2026-07-22" "M4KK1 1.0" "M4KK1 系统调用"
.SH 名称
m4k_register_session \- 注册登录会话
.SH 概要
.nf
#include <m4k/syscall.h>
int m4k_register_session(const char *tty, uid_t uid, const char *username);
.fi
.SH 描述
在 /sys/sessions/ 中注册一个新的登录会话，用于 who 和 userlog 命令。
.SH 返回值
成功返回 0，失败返回负的 M4K_E* 错误码。
.SH 参见
.BR m4k_get_session_list (2),
.BR who (1)
